name: build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: dotnet restore
      working-directory: CSharp/
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: CSharp/
    - name: Test
      run: dotnet test --no-restore --verbosity normal --collect:"XPlat Code Coverage"
      working-directory: CSharp/
    - name: Publish code coverage reports to codecove.io
      uses: codecov/codecov-action@v1
      with:
        token: '677ee59c-a054-4db9-8ce5-09572125a475'
        files: ./**/coverage.cobertura.xml
        fail_ci_if_error: true
